baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'MyHuggy'
theme = 'ga-hugo-theme'

[module]
[[module.imports]]
    path = '../layouts/video-js'

[params]
  [params.video_js]
    css_url = 'https://unpkg.com/video.js/dist/video-js.min.css'
    js_url = 'https://unpkg.com/video.js/dist/video.min.js'
